export const FETCH_STOCK_DATA = "FETCH_STOCK_DATA";
export const START_FETCH_STOCK_DATA = "START_FETCH_STOCK_DATA";
export const STOP_FETCH_STOCK_DATA = "STOP_FETCH_STOCK_DATA";

export const FETCH_DAILY_STOCK_DATA = "FETCH_DAILY_STOCK_DATA";
export const START_DAILY_FETCH_STOCK_DATA = "START_DAILY_FETCH_STOCK_DATA";
export const STOP_DAILY_FETCH_STOCK_DATA = "STOP_DAILY_FETCH_STOCK_DATA";

export const FETCH_SEARCH_STOCK_DATA = "FETCH_SEARCH_STOCK_DATA";
export const START_SEARCH_STOCK_DATA = "START_SEARCH_STOCK_DATA";
export const STOP_SEARCH_STOCK_DATA = "STOP_SEARCH_STOCK_DATA";

export const STOP_CHART_DISPLAY = "STOP_CHART_DISPLAY";
